Repository grumpycoders/pcsx-redux, pull requests merged in 2025-07, with the labels that each got.

#1947 Sorting out yet another AppImage breakage.
  .github/workflows/linux-build.yml
  tools/build/Dockerfile
  tools/build/appimage-dpkg.patch
Labels: size/M

#1946 Fixing accesses to the pcsx IO system.
  src/mips/common/hardware/pcsxhw.h
  src/mips/psyqo/examples/pcsxlua/pcsxlua.cpp
Labels: size/S

#1944 autoring: add -q option
  tools/authoring/authoring.cc
Labels: size/S

#1940 chore: create readme with community examples
  .github/workflows/linux-toolchain.yml
  src/mips/psyqo/examples/README.md
Labels: size/XS
