Repository grumpycoders/pcsx-redux, pull requests merged in 2025-08, with the labels that each got.

#1951 Switching to linuxdeploy.
  .github/workflows/linux-build.yml
  Makefile
  dockermake-cross.sh
  dockermake.sh
  dockershell.sh
  src/support/version-linux.cc
  tools/build/Dockerfile
  tools/build/appimage-dpkg.patch
Labels: size/M

#1952 Fix GDB packet p (readRegister)
  src/core/gdb-server.cc
Labels: size/XS

#1954 Add monitor command to retrieve the shared memory name. Only for wram so far
  src/core/gdb-server.cc
  src/core/psxmem.h
  src/support/sharedmem-windows.cc
  src/support/sharedmem.h
Labels: size/S

#1956 a64 JIT: Fix `setRWX` returning nothing on Apple
  src/core/DynaRec_aa64/emitter.h
  src/core/DynaRec_aa64/recompiler.cc
Labels: size/XS

#1958 arm64 JIT: Fix broken cache invalidation
  src/core/DynaRec_aa64/recompiler.h
Labels: size/XS

#1955 MacOS bundling fixes
  .github/scripts/create-app.sh
  .gitignore
Labels: size/XS
